Fix codeclimate depends/SDKs exclusion path
Due to an oversight the exclusion path mismatched the
path advised in depends/README.md.
Thus if the SDK was unpacked in depends/ according to
instructions, running CodeClimate would still lead to
an error while processing the SDK files.

Test plan (needs Docker to run CodeClimate)
-------------------------------------------

```
cd depends
mkdir SDKs
tar -C SDKs -xf /path/to/MacOSX10.14.sdk.tar.xz
docker run --interactive --tty --rm --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate analyze
```

The CodeClimate analysis should complete. Without this
patch, it would abort with an error as below while trying
to process the SDK:

```
error: (CC::CLI::Analyze::EngineFailure) engine shellcheck failed with status 1 and stderr
engine: depends/SDKs/MacOSX10.14.sdk/usr/bin/krb5-config: hGetContents: invalid argument (invalid byte sequence)
engine: thread blocked indefinitely in an MVar operation
```