[build-configurations] Resurface the more informative error message when ABC_BUILD_NAME is not set
Summary: D3992 ended up masking this error message.  Since the custom error message is more informative, I decided to move `set -u` instead of removing the message entirely.  Not having `set -u` set after simple error messages like this should have negligible effect.

Test Plan:
Run:
```
./build-configurations.sh
```

Result before patch:
```
./build-configurations.sh: line 7: ABC_BUILD_NAME: unbound variable
```

Result after patch:
```
+ '[' -z '' ']'
+ echo 'Error: Environment variable ABC_BUILD_NAME must be set'
Error: Environment variable ABC_BUILD_NAME must be set
+ exit 1
```

Reviewers: #bitcoin_abc, deadalnix

Reviewed By: #bitcoin_abc, deadalnix

Differential Revision: https://reviews.bitcoinabc.org/D4214